# Use an official node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json the package-lock.json files to the container
COPY package*.json .

# Install the dependencies
RUN npm Install

# Copy the rest of the application code // first . is the current directory of our local folder, second . is the current workdir of our docker enviroment
COPY . .

# Expose the port that the app runs on
EXPOSE 3000

# Define the command to run your application
CMD ['node', './src/app.js']